// THIS FILE IS AUTOGENERATED FROM ant/master/master.proto

#ifndef KUDU_RPC_MASTER_SERVICE_IF_DOT_H
#define KUDU_RPC_MASTER_SERVICE_IF_DOT_H

#include "ant/master/master.pb.h"

#include <functional>
#include <memory>
#include <string>

#include "ant/rpc/rpc_header.pb.h"
#include "ant/rpc/service_if.h"

namespace ant {
class MetricEntity;
namespace rpc {
class Messenger;
class ResultTracker;
class RpcContext;
} // namespace rpc
} // namespace ant

namespace ant {
namespace master {

class MasterServiceIf : public ::ant::rpc::GeneratedServiceIf {
 public:
  explicit MasterServiceIf(const scoped_refptr<MetricEntity>& entity, const scoped_refptr<rpc::ResultTracker>& result_tracker);
  virtual ~MasterServiceIf();
  std::string service_name() const override;
  static std::string static_service_name();

  virtual void Ping(const PingRequestPB *req,
     PingResponsePB *resp, ::ant::rpc::RpcContext *context) = 0;
  virtual void WorkerHeartbeat(const WorkerHeartbeatRequestPB *req,
     WorkerHeartbeatResponsePB *resp, ::ant::rpc::RpcContext *context) = 0;

};

} // namespace master
} // namespace ant

#endif
