// THIS FILE IS AUTOGENERATED FROM ant/master/master.proto

#ifndef KUDU_RPC_MASTER_PROXY_DOT_H
#define KUDU_RPC_MASTER_PROXY_DOT_H

#include "ant/master/master.pb.h"

#include "ant/rpc/proxy.h"
#include "ant/util/status.h"

namespace ant { class Sockaddr; }
namespace ant { namespace rpc { class UserCredentials; } }
namespace ant {
namespace master {


class MasterServiceProxy : public ::ant::rpc::Proxy {
 public:
  MasterServiceProxy(const std::shared_ptr< ::ant::rpc::Messenger>
                &messenger, const ::ant::Sockaddr &sockaddr);
  ~MasterServiceProxy();


  ::ant::Status Ping(const PingRequestPB &req, PingResponsePB *resp,
                          ::ant::rpc::RpcController *controller);
  void PingAsync(const PingRequestPB &req,
                       PingResponsePB *response,
                       ::ant::rpc::RpcController *controller,
                       const ::ant::rpc::ResponseCallback &callback);

  ::ant::Status WorkerHeartbeat(const WorkerHeartbeatRequestPB &req, WorkerHeartbeatResponsePB *resp,
                          ::ant::rpc::RpcController *controller);
  void WorkerHeartbeatAsync(const WorkerHeartbeatRequestPB &req,
                       WorkerHeartbeatResponsePB *response,
                       ::ant::rpc::RpcController *controller,
                       const ::ant::rpc::ResponseCallback &callback);
};

} // namespace master
} // namespace ant

#endif
