// THIS FILE IS AUTOGENERATED FROM ant/tests/rpc/rtest.proto

#ifndef KUDU_RPC_RTEST_SERVICE_IF_DOT_H
#define KUDU_RPC_RTEST_SERVICE_IF_DOT_H

#include "ant/tests/rpc/rtest.pb.h"

#include <functional>
#include <memory>
#include <string>

#include "ant/rpc/rpc_header.pb.h"
#include "ant/rpc/service_if.h"

namespace ant {
class MetricEntity;
namespace rpc {
class Messenger;
class ResultTracker;
class RpcContext;
} // namespace rpc
} // namespace ant

namespace ant {
namespace rpc_test {

class CalculatorServiceIf : public ::ant::rpc::GeneratedServiceIf {
 public:
  explicit CalculatorServiceIf(const scoped_refptr<MetricEntity>& entity, const scoped_refptr<rpc::ResultTracker>& result_tracker);
  virtual ~CalculatorServiceIf();
  std::string service_name() const override;
  static std::string static_service_name();

  virtual void Add(const AddRequestPB *req,
     AddResponsePB *resp, ::ant::rpc::RpcContext *context) = 0;
  virtual void Sleep(const SleepRequestPB *req,
     SleepResponsePB *resp, ::ant::rpc::RpcContext *context) = 0;
  virtual void Echo(const EchoRequestPB *req,
     EchoResponsePB *resp, ::ant::rpc::RpcContext *context) = 0;
  virtual void WhoAmI(const WhoAmIRequestPB *req,
     WhoAmIResponsePB *resp, ::ant::rpc::RpcContext *context) = 0;
  virtual void TestArgumentsInDiffPackage(const ant::rpc_test_diff_package::ReqDiffPackagePB *req,
     ant::rpc_test_diff_package::RespDiffPackagePB *resp, ::ant::rpc::RpcContext *context) = 0;
  virtual void Panic(const PanicRequestPB *req,
     PanicResponsePB *resp, ::ant::rpc::RpcContext *context) = 0;
  virtual void AddExactlyOnce(const ExactlyOnceRequestPB *req,
     ExactlyOnceResponsePB *resp, ::ant::rpc::RpcContext *context) = 0;
  virtual void TestInvalidResponse(const TestInvalidResponseRequestPB *req,
     TestInvalidResponseResponsePB *resp, ::ant::rpc::RpcContext *context) = 0;

};

} // namespace rpc_test
} // namespace ant

#endif
